// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa-tMMR94UMxpbiJCmQ7aiSOLKkKKYcpM',
    appId: '1:609955553896:web:e550348398558df46dd1dd',
    messagingSenderId: '609955553896',
    projectId: 'walk-win-602a2',
    authDomain: 'walk-win-602a2.firebaseapp.com',
    databaseURL: 'https://walk-win-602a2-default-rtdb.firebaseio.com',
    storageBucket: 'walk-win-602a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk3xXBPr5vSh_Oi9q3ftZoGLjGbTcAbxg',
    appId: '1:609955553896:android:83572f1139af09cf6dd1dd',
    messagingSenderId: '609955553896',
    projectId: 'walk-win-602a2',
    databaseURL: 'https://walk-win-602a2-default-rtdb.firebaseio.com',
    storageBucket: 'walk-win-602a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4t26zzyf-np0nER8aldY_hfU_ooOC72o',
    appId: '1:609955553896:ios:eff9ff853c99f0bf6dd1dd',
    messagingSenderId: '609955553896',
    projectId: 'walk-win-602a2',
    databaseURL: 'https://walk-win-602a2-default-rtdb.firebaseio.com',
    storageBucket: 'walk-win-602a2.appspot.com',
    iosBundleId: 'com.example.fluttProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4t26zzyf-np0nER8aldY_hfU_ooOC72o',
    appId: '1:609955553896:ios:3a6ff9894793e85b6dd1dd',
    messagingSenderId: '609955553896',
    projectId: 'walk-win-602a2',
    databaseURL: 'https://walk-win-602a2-default-rtdb.firebaseio.com',
    storageBucket: 'walk-win-602a2.appspot.com',
    iosBundleId: 'com.example.fluttProject1.RunnerTests',
  );
}
